spring.application.name=licensexpress
application.startup.adminUsername=admin
application.startup.adminEmail=admin@example.com
application.startup.adminPassword=password
application.allow-self-registration=false

#Spring Data Settings
spring.datasource.url=jdbc:mysql://localhost:3306/license_xpress
spring.datasource.username=user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

#Email Settings
application.email.enable-auth=true
application.email.enable-starttls=true
application.email.host=test
application.email.port=587
application.email.from-address=no-reply@example.com
application.email.username=username
application.email.password=password